config/routes.rb
Rails.application.routes.draw do
  #resource :NewsArticles

  root 'home_page#index'
  get 'news_page/index'
  get 'contacts/index'
  get 'about/index'

  get 'news_page/business'
  get 'news_page/politics'
  get 'news_page/technology'
  get 'news_page/entertainment'
  get 'news_page/weather'
  get 'news_page/post'
  post 'news_page/post_create'
  get  'forum_page/index'
  get 'signin/index'


end

app/models/news_article.rb
class NewsArticle < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
end
end

app/controllers/forum_page_controller.rb
class ForumPageController < ApplicationController
  def index

  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
def index
  @imageNames = []#["syria.jpg", "kenyauni.jpg", "GAMBIA.jpeg"]

  @articles = NewsArticle.all()

  @articles.each do |article|
    @imageNames.append(article.image_url)

  end
end
end

app/controllers/news_page_controller.rb
class NewsPageController < ApplicationController
def index
  #@news_page = News_page.all
end

  def politics
  end

  def business
  end

def technology

end

  def entertainment
  end

def weather

end

  def post

  end

  def post_create
    #render plain: params[:article].inspect
    paramsToUse = params.require(:article).permit(:headline, :body, :video_url, :image_url)
    newArticle = NewsArticle.new(paramsToUse)
    newArticle.save()

    redirect_to root_path
  end

def forum

end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def index

  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/forum_page_helper.rb
module ForumPageHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/news_page_helper.rb
module NewsPageHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/views/forum_page/index.html.erb
<!DOCTYPE html>
<html lang="en">

<div class="container">
  <h2>Forum</h2>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>News Title</th>
      <th>Time-Date</th>
      <th>Last User</th>
      <th>Number of comments</th>

    </tr>
    </thead>
    <tbody>
    <tr>
      <td>Syria War</td>
      <td>20-08-2016 10:51am</td>
      <td>John</td>
      <td>50</td>
    </tr>
    <tr>
      <td>Holiday destinations</td>
      <td>20-08-2016 10:51am</td>
      <td>mary</td>
      <td>50</td>
    </tr>
    <tr>
      <td>Floods in Lousiana</td>
      <td>20-08-2016 10:51am</td>
      <td>july</td>
      <td>50</td>
    </tr>
    </tbody>
  </table>
</div>



</html>

app/views/home_page/index.html.erb
Welcome to Africa's latest

<%= link_to('post article', news_page_post_path)%>



<% @imageNames.each do |imgName| %>

    <div class="row">

      <div class="col-sm-4 col-md-4">
        <div class="thumbnail">
          <%= image_tag(imgName) %>
          <div class="caption">
            <h3>Syria</h3>
            <p>...</p>
            <p><a href="#" class="btn btn-primary" role="button">Button</a>
              <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
      </div>

      <div class="col-sm-4 col-md-4">
        <div class="thumbnail">
          <%= image_tag(imgName) %>
          <div class="caption">
            <h3>kenya</h3>
            <p>...</p>
            <p><a href="#" class="btn btn-primary" role="button">Button</a>
              <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
      </div>

    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstRailsSample</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<style>
  body {
    background-color: linen;
  }

  ul {
    color: maroon;
    margin-left: 40px;
  }

  .affix {
    top: 0;
    width: 100%;
  }

  .affix + .container-fluid {
    padding-top: 70px;
  }
</style>




<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="197">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Africa's Latest</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">News
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to('Politics', news_page_politics_path) %></li>
          <li><%= link_to('Business', news_page_business_path) %></li>
          <li><%= link_to('Technology', news_page_technology_path) %></li>
          <li><%= link_to('Entertainment', news_page_entertainment_path) %></li>
          <li><%= link_to('Weather', news_page_weather_path) %></li>
        </ul>
      </li>

      <li class="active"><a href="/forum_page/index">Forum</a></li>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>



          <li style="float:right"><a class="active" href="/signin/index">Sign in</a></li>


    </ul>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/news_page/business.html.erb
News will be up soon!!

app/views/news_page/entertainment.html.erb
News will be up soon!!

app/views/news_page/index.html.erb
News will be up soon!!

app/views/news_page/politics.html.erb
News will be up soon!!

app/views/news_page/post.html.erb
<%= form_for :article, url: news_page_post_create_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :headline %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.label :video %><br>
      <%= f.text_field :video_url %>
    </p>
    <p>
      <%= f.label :image %><br>
      <%= f.text_field :image_url %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/news_page/technology.html.erb
News will be up soon!!

app/views/news_page/weather.html.erb
News will be up soon!!

app/views/signin/index.html.erb
<form>
  <div class="form-group">
    <label for="email">Email address:</label>
    <input type="email" class="form-control" id="email">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" id="pwd">
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>